//! Base94Max: a port of the JavaScript implementation in this repository's
//! `index.js`.
//!
//! The encoding packs the input into blocks of 13 or 14 bits, choosing between
//! the two per block, and writes each block as two characters drawn from the 94
//! printable ASCII characters `!` through `~`. The choice is what makes it
//! adaptive: 14 bits are taken whenever the low 13 bits are small enough that
//! the resulting block still fits in two base-94 digits, and 13 bits otherwise.
//! Two digits carry `94 * 94 - 1 = 8835` values, so the threshold is that
//! number's low 13 bits.
//!
//! ```
//! let encoded = base94max::encode(b"Hello");
//! assert_eq!(base94max::decode(&encoded).unwrap(), b"Hello");
//! ```
//!
//! The port is checked against vectors generated by `index.js` itself
//! (`testvectors/base94max.json`), so the two implementations are known to
//! agree character for character rather than assumed to.

#![forbid(unsafe_code)]

use std::fmt;

/// The number of characters in the alphabet.
const BASE: u32 = 94;

/// The alphabet is ASCII 33..=126 in order, so a value maps to a character by
/// addition and no lookup table is needed. This is the `PRINTABLE` variant of
/// `index.js`; the deprecated `JSON_DELETE` variant is not ported.
const FIRST: u8 = b'!';
const LAST: u8 = b'~';

/// `(94 * 94 - 1) & 0x1FFF`. A block of 14 bits is only taken when the low 13
/// bits do not exceed this, because beyond it the block would need a third
/// base-94 digit.
const MAX_14BIT_THRESHOLD: u32 = 643;

/// Characters that carry no data and are skipped while decoding, so that
/// line-wrapped or newline-terminated input decodes without preprocessing.
/// None of them is in the alphabet, so nothing is lost by ignoring them.
const fn is_skippable_whitespace(c: u8) -> bool {
    matches!(c, 0x09 | 0x0a | 0x0b | 0x0c | 0x0d | 0x20)
}

/// Why a string could not be decoded.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum DecodeError {
    /// A character that is neither in the alphabet nor ignorable whitespace.
    InvalidCharacter { position: usize, byte: u8 },
    /// The trailing bits were not zero, which no encoder output produces: the
    /// input was truncated, reordered, or not this encoding at all.
    TrailingBits,
}

impl fmt::Display for DecodeError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            DecodeError::InvalidCharacter { position, byte } => write!(
                f,
                "invalid character in Base94Max string at position {position}: {:?}",
                *byte as char
            ),
            DecodeError::TrailingBits => {
                f.write_str("invalid Base94Max padding: trailing bits are not zero")
            }
        }
    }
}

impl std::error::Error for DecodeError {}

/// The exact number of characters `encode` will produce for `len` input bytes,
/// in the worst case. Every block consumes at least 13 bits and yields two
/// characters, plus at most two for the trailing partial block.
fn encoded_len_upper_bound(len: usize) -> usize {
    (len * 8).div_ceil(13) * 2 + 2
}

/// Encodes binary data into a Base94Max string.
///
/// The output is ASCII and contains only the characters `!` through `~`.
pub fn encode(data: &[u8]) -> String {
    let mut out = Vec::with_capacity(encoded_len_upper_bound(data.len()));
    let mut bit_buf: u32 = 0;
    let mut bit_count: u32 = 0;

    for &byte in data {
        bit_buf |= (byte as u32) << bit_count;
        bit_count += 8;

        // At most one block closes per byte -- eight bits in cannot close two
        // blocks of thirteen -- but the loop states the invariant rather than
        // relying on that.
        while bit_count >= 14 {
            let block = if (bit_buf & 0x1FFF) > MAX_14BIT_THRESHOLD {
                let block = bit_buf & 0x1FFF;
                bit_buf >>= 13;
                bit_count -= 13;
                block
            } else {
                let block = bit_buf & 0x3FFF;
                bit_buf >>= 14;
                bit_count -= 14;
                block
            };
            // Little digit first, which is the order `index.js` writes and so
            // the order the format has.
            out.push(FIRST + (block % BASE) as u8);
            out.push(FIRST + (block / BASE) as u8);
        }
    }

    if bit_count > 0 {
        out.push(FIRST + (bit_buf % BASE) as u8);
        // A second digit only when the remainder needs one: either the value
        // does not fit in a single digit, or more than a byte is still held.
        if bit_buf >= BASE || bit_count > 8 {
            out.push(FIRST + (bit_buf / BASE) as u8);
        }
    }

    // Every byte pushed came from `FIRST + v` with `v < BASE`, so the buffer is
    // ASCII by construction.
    String::from_utf8(out).expect("alphabet is ASCII")
}

/// Decodes a Base94Max string back into binary data.
///
/// Whitespace outside the alphabet is ignored, so input that was wrapped across
/// lines decodes as it stands.
pub fn decode(s: &str) -> Result<Vec<u8>, DecodeError> {
    let bytes = s.as_bytes();
    let mut out = Vec::with_capacity(bytes.len() * 13 / 16 + 1);
    let mut bit_buf: u32 = 0;
    let mut bit_count: u32 = 0;
    // The low digit of a block, held until its high digit arrives.
    let mut pending: Option<u32> = None;

    for (position, &c) in bytes.iter().enumerate() {
        if !(FIRST..=LAST).contains(&c) {
            if is_skippable_whitespace(c) {
                continue;
            }
            return Err(DecodeError::InvalidCharacter { position, byte: c });
        }
        let value = (c - FIRST) as u32;

        match pending.take() {
            None => pending = Some(value),
            Some(low) => {
                let block = low + value * BASE;
                bit_buf |= block << bit_count;
                // The same test the encoder made, read back off the block: it
                // is what says whether this block carried 13 bits or 14.
                bit_count += if (block & 0x1FFF) > MAX_14BIT_THRESHOLD { 13 } else { 14 };

                while bit_count >= 8 {
                    out.push((bit_buf & 0xFF) as u8);
                    bit_buf >>= 8;
                    bit_count -= 8;
                }
            }
        }
    }

    // A trailing single digit is the partial block the encoder wrote for the
    // last few bits.
    if let Some(low) = pending {
        bit_buf |= low << bit_count;
        out.push((bit_buf & 0xFF) as u8);
        bit_buf >>= 8;
    }

    if bit_buf != 0 {
        return Err(DecodeError::TrailingBits);
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn empty_round_trips() {
        assert_eq!(encode(b""), "");
        assert_eq!(decode("").unwrap(), b"");
    }

    #[test]
    fn output_is_within_the_alphabet() {
        let data: Vec<u8> = (0..=255u8).cycle().take(1000).collect();
        assert!(encode(&data).bytes().all(|c| (FIRST..=LAST).contains(&c)));
    }

    #[test]
    fn whitespace_between_symbols_is_ignored() {
        let encoded = encode(b"the quick brown fox");
        let wrapped: String = encoded
            .as_bytes()
            .chunks(4)
            .map(|c| String::from_utf8(c.to_vec()).unwrap())
            .collect::<Vec<_>>()
            .join("\n");
        assert_eq!(decode(&wrapped).unwrap(), b"the quick brown fox");
    }

    #[test]
    fn characters_outside_the_alphabet_are_rejected() {
        assert_eq!(
            decode("ab\u{7f}cd"),
            Err(DecodeError::InvalidCharacter { position: 2, byte: 0x7f })
        );
    }

    #[test]
    fn round_trips_every_length_up_to_a_kilobyte() {
        // xorshift32, the same generator the vector file documents, so a
        // failure here can be reproduced in either language.
        let mut s: u32 = 0x1234_5678;
        let mut next = || {
            s ^= s << 13;
            s ^= s >> 17;
            s ^= s << 5;
            (s & 0xff) as u8
        };
        let data: Vec<u8> = (0..1024).map(|_| next()).collect();
        for len in 0..=1024 {
            let slice = &data[..len];
            assert_eq!(decode(&encode(slice)).unwrap(), slice, "length {len}");
        }
    }
}
